* MARAVILHOSA TELA INICIAL
** DEPENDENZAS DO DASHBOARD
*** page-break-lines
#+BEGIN_SRC emacs-lisp
  (use-package page-break-lines
    :ensure t)
#+END_SRC
*** projectile
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (projectile-mode +1)
    :bind
    ("S-p" . projectile-command-mode))

#+END_SRC
** pagina inicial em si
#+BEGIN_SRC emacs-lisp
  ;; ANTIGO BUFFER
  ;;(defun my-buffeiro ()
  ;;  (let ((buffer (generate-new-buffer "intro")))
  ;;    (switch-to-buffer buffer)
  ;;    (center-line)
  ;;    (insert "BEM VINDO AO MARAVILHOSO IMAKKUSU\n")
  ;;    (insert-image (create-image "~/.emacs.d/img/kicchiri.png"))
  ;;    (insert "\n\n\n\n\n")
  ;;    buffer))
  ;;(setq initial-buffer-choice 'my-buffeiro)

  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
     (setq dashboard-banner-logo-title "BEM VINDO AO MARAVILHOSO IMAKKUSU")
     (setq dashboard-startup-banner (concat (getenv "XDG_CONFIG_HOME") "/emacs/img/kicchiri.png"))
     (setq dashboard-center-content t)
     (setq dashboard-show-shortcuts nil)
     (setq dashboard-items '((recents . 20)
			     (bookmarks . 5)
			     (agenda . 10)
			     (projects . 5)))
     (setq dashboard-set-heading-icons t)
     (setq dashboard-set-file-icons t)
     (dashboard-modify-heading-icons '((recents . "ruby")
				       (bookmarks . "bookmark" )
				       (projects . "package" )))
     ;; adds agenda 
     (setq show-week-agenda-p t)

     (setq dashboard-footer-messages '("emags :DDDDDDDD"))
     (setq initial-buffer-choice (lambda () (get-buffer "*dashboard*"))))
#+END_SRC


*Garanta que a imagem existe pls*

* Configurações visuais
** Fonte
#+BEGIN_SRC emacs-lisp
(setq default-frame-alist '((font . "Hack 12")))

#+END_SRC
Força por padrão a fonte Hack, tamanho 12

** Barra de tarefas
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)

#+END_SRC
Remove *toda* a barra de tarefas

** Barra de menu
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)

#+END_SRC
Menu é inútil e toma espaço

** Highlight de linha
#+BEGIN_SRC emacs-lisp
(global-hl-line-mode t)
#+END_SRC

*LINHAS CHAMAM MAIS ATENÇÃO AGR*

** TEMA ATUAL
#+BEGIN_SRC emacs-lisp
  (use-package sublime-themes
     :ensure t
     :init
     (load-theme 'brin t))

#+END_SRC
Combina mais com o tema atual do meu desktop environment
** modeline
#+BEGIN_SRC emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1)
  :config 
  (setq doom-modeline-mu4e t)
  (setq doom-modeline-bar-width 1)
  (setq doom-modeline-icon 1))
#+END_SRC
** line numbers
#+BEGIN_SRC emacs-lisp
  (defun mostrarLinhazitas ()
      (interactive)
      (display-line-numbers-mode))
  (add-hook 'prog-mode-hook 'mostrarLinhazitas)

#+END_SRC
** Barra de scroll(?)
#+BEGIN_SRC emacs-lisp
  (scroll-bar-mode -1)
#+END_SRC
** Pretty symbols
#+begin_src emacs-lisp
(global-prettify-symbols-mode t)
#+end_src
** all-the-icons
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
    :ensure t)

#+END_SRC
* PACOTES GERAIS
** define-word
   #+begin_src emacs-lisp
     (use-package define-word
       :ensure t
       :bind
       ("C-c d" . define-word)
       ("C-c u" . define-word-at-point))

   #+end_src
   Bom para procurar significado de palavras.

** undo-tree
#+begin_src emacs-lisp
(use-package undo-tree
  :ensure t
  :config
  (global-undo-tree-mode))
#+end_src
** pyenv
#+BEGIN_SRC emacs-lisp
  (use-package pyenv-mode
    :ensure t
    :ensure-system-package pyenv
    :hook
    (pyenv-mode . python-mode))
#+END_SRC
Permite-me trabalhar com ambientes virtuais
** magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :bind
    ("C-x g" . magit-status))
#+END_SRC
** neotree
#+BEGIN_SRC emacs-lisp
  (use-package neotree
    :ensure t
    :config
    (global-set-key (kbd "s-n") 'neotree-toggle)
    (setq neo-theme (if (display-graphic-p) 'icons 'arrow)))

#+END_SRC
** column enforce mode
#+BEGIN_SRC emacs-lisp
  (use-package column-enforce-mode
    :ensure t
    :config
    (add-hook 'prog-mode-hook 'column-enforce-mode)
    (add-hook 'text-mode-hook 'column-enforce-mode))
#+END_SRC
Enforça a regra dos 80(?) caracteres em uma linha, ou pelo menos
só mostra um limite
** *Which key*
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :init
  (which-key-mode))

#+END_SRC
** avy
#+BEGIN_SRC emacs-lisp
  (use-package avy
    :ensure t
    :bind
    ("M-." . avy-goto-char)
    ("M-g f" . avy-goto-line))
#+END_SRC
** Rainbow
*** Rainbow-delimiters
#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))

#+END_SRC
*** Rainbow mode
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t
    :hook
    (prog-mode . rainbow-mode))
#+END_SRC
Códigos de cor *hexadecimais* ficam coloridos yay
** smart tabs
#+BEGIN_SRC emacs-lisp
(use-package smart-tabs-mode
 :ensure t
 :config
 (smart-tabs-add-language-support latex latex-mode-hook
 ((latex-indent-line . 4)
 (latex-indent-region . 4)))
 (smart-tabs-insinuate 'c 'c++ 'java 'latex)
 (smart-tabs-advice js2-indent-line js2-basic-offset))

#+END_SRC
esse código copiei de um anão
** Switch window
#+BEGIN_SRC emacs-lisp
  (use-package switch-window
    :ensure t
    :config
    (setq switch-window-input-style 'minibuffer)
    (setq switch-window-increase 4)
    (setq switch-window-threshold 2)
    :bind
    ([remap other-window] .  switch-window))
#+END_SRC
** autocompletion
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :config
    (setq company-idle-delay 0)
    (setq company-minimum-prefix-length 2)
    (setq company-selection-wrap-around t)
    (company-tng-configure-default)
    :hook
    (after-init . global-company-mode)
    :bind
    ("s-c" . company-complete))
#+END_SRC
*** company-irony
#+BEGIN_SRC emacs-lisp
  (use-package company-irony
    :ensure t
    :after company 
    :init
    (add-to-list 'company-backends 'company-irony))
#+END_SRC
*** ac-js2
#+BEGIN_SRC emacs-lisp
  (use-package ac-js2
    :ensure t
    :after company
    :init
    (add-to-list 'company-backends 'ac-js2-company))
#+END_SRC
Para javascripto/jsx
*** company-anaconda
#+BEGIN_SRC emacs-lisp
  (use-package company-anaconda
    :ensure t
    :after company
    :init
    (add-to-list 'company-backends 'company-anaconda)
    :hook
    (python-mode . anaconda-mode))
#+END_SRC
Autocomplete para python 
*** company-latex
**** auctex
#+BEGIN_SRC emacs-lisp
  (use-package company-auctex
    :ensure t
    :after company 
    :init
    (add-to-list 'company-backends 'company-auctex)
    (company-auctex-init))
#+END_SRC
Autocomplete para latex tags
**** math-symbols
#+BEGIN_SRC emacs-lisp
    (use-package company-math
      :ensure t
      :after company 
      :init
      (add-to-list 'company-backends 'company-math-symbols-unicode))
#+END_SRC
*** quickhelp
#+BEGIN_SRC emacs-lisp
  (use-package company-quickhelp
    :ensure t
    :init
    (setq company-quickhelp-delay 0)
    :hook
    (prog-mode . company-quickhelp-mode))
#+END_SRC
Mostra documentação automaticamente

*** company-c-headers
#+BEGIN_SRC emacs-lisp
    (use-package company-c-headers
      :ensure t
      :after company 
      :init
      (add-to-list 'company-backends 'company-c-headers))

#+END_SRC
** flycheck
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :init
    (global-flycheck-mode t))

#+END_SRC
** dmenu
#+BEGIN_SRC emacs-lisp
  (use-package dmenu
    :ensure t
    :bind
    ("s-d" . 'dmenu))
#+END_SRC
pode me ajudar na *multitarefagem*
** browse kill ring
#+BEGIN_SRC emacs-lisp
  (use-package browse-kill-ring
    :ensure t
    :bind
    ("M-y" . 'browse-kill-ring))

#+END_SRC
** Swiper
#+BEGIN_SRC emacs-lisp
    (use-package ivy
      :ensure t
      :config
      (ivy-mode 1)
      (setq ivy-use-virtual-buffers t)
      (setq enable-recursive-minibuffers t))
#+END_SRC
Boa função para procurar, mostra as ocorrências num minibuffer 
*** swiper
#+begin_src emacs-lisp
  (use-package swiper
    :ensure t
    :after ivy
    :bind
    ("C-s" . swiper))
#+end_src
*** Counsel
#+begin_src emacs-lisp 
  (defun preservar-output ()
    (interactive)
    (let ((input (ivy--input)))
      (ivy-quit-and-run (counsel-file-jump))))

  (use-package counsel
    :ensure t
    :after ivy
    :config
    (define-key ivy-minibuffer-map (kbd "TAB") 'ivy-partial)
    (define-key counsel-find-file-map (kbd "s-j") 'preservar-output)
    :bind
    ("M-x" . counsel-M-x)
    ("C-x C-f" . counsel-find-file)
    ("C-c m" . counsel-imenu))

#+end_src

#+BEGIN_CENTER
Entretanto, pode bugar em buffers maiores
#+END_CENTER
** multiple cursors
#+BEGIN_SRC emacs-lisp
  (use-package multiple-cursors
    :ensure t
    :bind
    ("C-c q" . 'mc/mark-next-like-this)
    ("C-c a" . 'mc/mark-all-like-this))

#+END_SRC
Pacote pra múltiplos cursores, muito daora
** expand region
#+BEGIN_SRC emacs-lisp
  (use-package expand-region
    :ensure t
    :bind
    ("C-c e" . er/expand-region))
#+END_SRC
#+BEGIN_CENTER
*EXPANDS EVERYTHING*
#+END_CENTER
** web-mode
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode)))

#+END_SRC
** sudo-edit
#+BEGIN_SRC emacs-lisp
  (use-package sudo-edit
    :ensure t
    :bind
	("C-c C-s" . sudo-edit))

#+END_SRC
** transpose-window
#+BEGIN_SRC emacs-lisp
  (use-package transpose-frame
    :ensure t)
#+END_SRC

Pacote para /management/ de janelas

** latex
*** auctex
#+BEGIN_SRC emacs-lisp
  (use-package tex
    :defer t
    :ensure auctex
    :hook
    (LaTeX-mode . visual-line-mode)
    (LaTeX-mode . flyspell-mode)
    (LaTeX-mode . LaTeX-math-mode)
    (LaTeX-mode . turn-on-reftex)
    :config
    (setq TeX-auto-save t)
    (setq TeX-parse-self t)
    (setq-default TeX-master nil)
    (setq reftex-plug-into-AUCTeX t)
    (setq TeX-PDF-mode t)
    (add-hook 'TeX-mode-hook
	      (lambda ()
		(setq TeX-command-extra-options "-shell-escape")
		)
	      ))

#+END_SRC 
Para edição aprimorada de documentos TEX
*** latex preview pane
#+BEGIN_SRC emacs-lisp
  (use-package latex-preview-pane
    :ensure t
    :hook
    (LaTeX-mode . latex-preview-pane-mode))
#+END_SRC
** gnuplot-mode
#+BEGIN_SRC emacs-lisp
(use-package gnuplot-mode
  :ensure t)
#+END_SRC
Para me auxiliar na plotagem de gráficos para a iniciação
** elfeed
#+begin_src emacs-lisp 
  (use-package elfeed
    :ensure t
    :init
    (setf url-queue-timeout 30)
    :bind
    ("C-x w" . elfeed))
  (use-package elfeed-goodies
    :ensure t
    :after elfeed)
#+end_src
** Pacotinhos pra mobile/web
*** JS2 mode
#+BEGIN_SRC emacs-lisp
  (use-package js2-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist '("\\.js\\'" . js2-mode))
    (add-to-list 'auto-mode-alist '("\\.jsx?\\'" . js2-jsx-mode))
    (add-to-list 'interpreter-mode-alist '("node" . js2-jsx-mode)))

#+END_SRC
*** simple-httpd
#+BEGIN_SRC emacs-lisp
  (use-package simple-httpd
    :ensure t)
#+END_SRC
servidor web "minimalista"

*** skewer mode
#+BEGIN_SRC emacs-lisp
  (use-package skewer-mode
    :ensure t
    :config
    (add-hook 'js2-mode-hook 'skewer-mode)
    (add-hook 'css-mode-hook 'skewer-css-mode)
    (add-hook 'html-mode-hook 'skewer-html-mode))

#+END_SRC
Interpretador de forms de html/css/js, também tem um repl
* TERMINAL
** Força zsh no ansi-term
#+BEGIN_SRC emacs-lisp
  (defvar default-shell "/bin/zsh")
  (defadvice ansi-term (before force-zsh)
    (interactive (list default-shell)))
  (ad-activate 'ansi-term)

#+END_SRC
Força zsh como shell do ansi-term

** Keybind
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "s-t") 'ansi-term)
#+END_SRC

* *GERAIS*
** mail encrypt
#+BEGIN_SRC emacs-lisp
(setq mm-sign-option 'guided)
(add-hook 'message-send-hook 'mml-secure-message-sign)
#+END_SRC
** ensure-system-package
#+BEGIN_SRC emacs-lisp
(use-package use-package-ensure-system-package
  :ensure t)

#+END_SRC
Pacotinho legal para garantir que pacotes externos existem (bom para o mu4e)
** Yes or No por Y or N
#+BEGIN_SRC emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)

#+END_SRC
** Ido mode
#+BEGIN_SRC emacs-lisp
  (setq ido-enable-flex-matching nil)
  (setq ido-create-new-buffer 'always)
  (setq ido-everywhere t)
  (ido-mode 1)

#+END_SRC
** enabling the current screen buffer (ibuffer)
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x b") 'ibuffer)

#+END_SRC
** switching buffers
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "s-s") 'ido-switch-buffer)

#+END_SRC

** assassino de palavras
#+BEGIN_SRC emacs-lisp
  (defun matarPalavra ()
    (interactive)
    (backward-word)
    (kill-word 1))
  (global-set-key (kbd "C-c DEL") 'matarPalavra)

#+END_SRC
** mostrar linhazitas
#+BEGIN_SRC emacs-lisp
  (line-number-mode 1)
  (column-number-mode 1)

#+END_SRC
** copiar linhazitas
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "C-c y") 'avy-copy-line)
#+END_SRC

** EMMS
#+BEGIN_SRC emacs-lisp
  ;; configs do uncle dave
  (use-package emms
    :ensure t
    :config
      (require 'emms-setup)
      (require 'emms-player-mpd)
      (emms-all) ; don't change this to values you see on stackoverflow questions if you expect emms to work
      (setq emms-seek-seconds 1)
      (setq emms-player-list '(emms-player-mpd))
      (setq emms-info-functions '(emms-info-mpd))
      (setq emms-player-mpd-server-name "localhost")
      (setq emms-player-mpd-server-port "6600")
    :bind
      ("s-m p" . emms)
      ("s-m b" . emms-smart-browse)
      ("s-m r" . emms-player-mpd-update-all-reset-cache)
      ("<C-XF86AudioPrev>" . emms-previous)
      ("<C-XF86AudioNext>" . emms-next)
      ("<C-XF86AudioPlay>" . emms-pause))
#+END_SRC
*** mpc
#+BEGIN_SRC emacs-lisp
(setq mpc-host "localhost:6000")

#+END_SRC
*** funcao para atualizar o database
#+BEGIN_SRC emacs-lisp
(defun mpd/update-database ()
  "Updates the MPD database synchronously."
  (interactive)
  (call-process "mpc" nil nil nil "update")
  (message "Database atualizado"))
(global-set-key (kbd "s-m u") 'mpd/update-database)

#+END_SRC
**** funcao para iniciar mpd
#+BEGIN_SRC emacs-lisp
(defun mpd/start-music-daemon ()
  "Start MPD, connects to it and syncs the metadata cache."
  (interactive)
  (shell-command "mpd")
  (mpd/update-database)
  (emms-player-mpd-connect)
  (emms-cache-set-from-mpd-all)
  (message "MPD atualizederson"))
(global-set-key (kbd "s-m c") 'mpd/start-music-daemon)
#+END_SRC
** autosave e backups
Configs roubadas de um anão 2.0
#+BEGIN_SRC emacs-lisp
  (setq-default backup-directory-alist
   '(("." . "~/.cache/emacs/backups/")))
  (add-to-list 'auto-save-file-name-transforms
   `(".*" "~/.cache/emacs/autosave/\\1" t) 'append)

#+END_SRC
** multimonitor

#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "s-'") 'other-frame)

#+END_SRC
Permite-me trocar facilmente por entre janelas
** Mover de acordo com camelCase
#+BEGIN_SRC emacs-lisp
  (global-subword-mode 1)
#+END_SRC
** Yasnippet
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :config
    (yas-reload-all)
    (add-hook 'prog-mode-hook 'yas-minor-mode))
#+END_SRC
*** Yasnippet snippets
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet-snippets
    :ensure t)

#+END_SRC
** aspell 
#+BEGIN_SRC emacs-lisp
(setq ispell-program-name "aspell")
#+END_SRC
Aspell me parece mais efetivo.
*** flyspell
#+BEGIN_SRC emacs-lisp
      (dolist (hook '(text-mode-hook))
	(add-hook hook (lambda () (flyspell-mode 1))))
      (dolist (hook '(change-log-mode-hook log-edit-mode-hook))
	(add-hook hook (lambda () (flyspell-mode -1))))
  (setq flyspell-issue-message-flag nil)
  (setq ispell-list-command "--list")
  ;; tudo copiado da wiki
  (global-set-key (kbd "<f8>") 'ispell-word)
  (global-set-key (kbd "C-S-<f8>") 'flyspell-mode)
  (global-set-key (kbd "C-M-<f8>") 'flyspell-buffer)
  (global-set-key (kbd "C-<f8>") 'flyspell-check-previous-highlighted-word)
  (defun flyspell-check-next-highlighted-word ()
    "Custom function to spell check next highlighted word"
    (interactive)
    (flyspell-goto-next-error)
    (ispell-word)
    )
  (global-set-key (kbd "M-<f8>") 'flyspell-check-next-highlighted-word)

#+END_SRC

** Forçar UTF-8
#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-language-environment 'utf-8)
#+END_SRC
** emacs daemon
#+BEGIN_SRC emacs-lisp
;; define function to shutdown emacs server instance
(defun matar-server ()
  "Save buffers, Quit, and Shutdown (kill) server"
  (interactive)
  (save-some-buffers)
  (kill-emacs)
  )

#+END_SRC
Roubado da wiki, esta funcao mata o daemon e pede para salvar os buffers
** mu4e
#+BEGIN_SRC emacs-lisp
  (use-package mu4e
    :ensure nil
    :ensure-system-package mu
    :load-path "/usr/share/emacs/site-lisp"
    :config
    ;; pastinhas
    (setq
     mu4e-maildir       "~/.local/share/Mail"   ;; top-level Maildir
     mu4e-sent-folder   "/Outlook/Enviadas"       ;; folder for sent m essages
     mu4e-trash-folder  "/Outlook/Deletadas"
     mu4e-refile-folder "/Outlook/INBOX"   ;; saved messages
     mu4e-attachment-dir "~/Downloads/Mail")


    (setq mu4e-get-mail-command "mbsync -c ~/.config/isync/mbsyncrc Outlookerson")

    ;; por enquanto este comando não está funcionando no momento
    ;; utilizando systemd no lugar
    ;; (mu4e-update-interval 240)
    (setq mu4e-enable-notifications t
	  ;; enable inline images
	  mu4e-view-show-images t
	  mu4e-index-update-error-warning t
	  mu4e-headers-auto-update t)

    (setq mu4e-change-filenames-when-moving t)
    ;; use imagemagick, if available
    (when (fboundp 'imagemagick-register-types)
      (imagemagick-register-types))
    (setq mu4e-use-fancy-chars t)
    ;; assinatura yay
    (setq user-mail-address "leon_bellini@outlook.com"
	  user-full-name "Leon Ferreira Bellini"
	  mu4e-compose-signature
	  (concat "Leon F. Bellini\n"
		  "Estudante de Ciência da Computação no Centro Universitário FEI\n"

		  "\nGitHub: https://github.com/seleonel\n")))


#+END_SRC
*** smtpmail
#+BEGIN_SRC emacs-lisp
  (use-package smtpmail
    :after mu4e
    :init
    (setq message-send-mail-function 'smtpmail-send-it
      smtpmail-stream-type 'starttls
      smtpmail-default-smtp-server "smtp.office365.com"
      smtpmail-smtp-server "smtp.office365.com"
      smtpmail-smtp-service 587))
;; todas as informações necessárias carregadas do ~/.authfile.gpg
#+END_SRC
cliente de email bem simples
*** mu4e-alert
#+BEGIN_SRC emacs-lisp
  (use-package mu4e-alert
    :ensure t
    :after mu4e
    :hook
    (after-init . mu4e-alert-enable-notifications)
    (after-init . mu4e-alert-enable-mode-line-display)
    :init
    (mu4e-alert-set-default-style 'libnotify)
       (setq mu4e-alert-interesting-mail-query
	     (concat
	      "flag:unread"
	      " AND NOT flag:trashed")))

#+END_SRC

** org-mode
*** Inline images
#+BEGIN_SRC emacs-lisp
  (setq org-display-inline-images t)
  (setq org-redisplay-inline-images t) 
  (setq org-startup-with-inline-images t)
  (setq org-image-actual-width 900)
  (with-eval-after-load 'org
    (add-hook 'org-babel-after-execute-hook
	      '(lambda ()
		 (when org-inline-image-overlays
		   (org-redisplay-inline-images)))))
#+END_SRC
Mostra por padrão as imagens no próprio buffer do org
*** gnuplot
#+BEGIN_SRC emacs-lisp
(use-package gnuplot
  :ensure t)
(use-package gnuplot-mode
  :ensure t)
#+END_SRC
*** gnuplot binding
#+BEGIN_SRC emacs-lisp
(local-set-key "M-C-g" 'org-plot/gnuplot) 
#+END_SRC
Gnuplot para plotagem de gráficos a partir de tabelas
*** plantuml
#+BEGIN_SRC emacs-lisp
  (setq org-plantuml-jar-path (expand-file-name (concat (getenv "XDG_DATA_HOME") "/plantuml/plantuml.jar")))
  (add-to-list 'org-src-lang-modes '("plantuml" . plantuml))
#+END_SRC
Programito bom para desenvolver diagramas de classes e fluxogramas.
**** plantuml-mode
#+BEGIN_SRC emacs-lisp
  (use-package plantuml-mode
    :ensure t
    :config
    (setq plantuml-jar-path (expand-file-name (concat (getenv "XDG_DATA_HOME") "/plantuml/plantuml.jar")))
    (setq plantuml-default-exec-mode 'jar))
#+END_SRC
*** belos simbolos
#+BEGIN_SRC emacs-lisp
  (add-hook 'org-mode-hook 'org-toggle-pretty-entities)
#+END_SRC
*** babel
#+BEGIN_SRC emacs-lisp
    (org-babel-do-load-languages 
     'org-babel-load-languages 
     '((plantuml . t) (python . t) (dot . t)))
#+END_SRC
Algumas opções de linguagens do babel
*** org-superstar
#+BEGIN_SRC emacs-lisp
  (use-package org-superstar
    :ensure t
    :hook
    (org-mode . (lambda () (org-superstar-mode 1)))
    :init
    (setq org-hide-leading-stars nil)
    (setq org-superstar-leading-bullet ?\s)
    (setq org-superstar-prettify-item-bullets t)
    (setq org-superstar-item-bullet-alist
	  '((?* . ?►)
	    (?+ . ?◐)
	    (?- . ?◆))))

#+END_SRC
Tae um bom nome.
*** org-roam
#+BEGIN_SRC emacs-lisp
    (use-package org-roam
      :ensure t
      :hook
      (after-init . org-roam-mode)
      :custom
      (org-roam-directory (concat (getenv "HOME") "/Estudo/arquivos-org/"))
      :bind (:map org-roam-mode-map
		  (("C-c n l" . org-roam)
		   ("C-c n f" . org-roam-find-file)
		   ("C-c n g" . org-roam-graph-show))
		  :map org-mode-map
		  (("C-c n i" . org-roam-insert)))
      :config
      (setq org-roam-index-file "./index.org")
      (require 'org-roam-protocol))
#+END_SRC
Bom pra brainstorming
** C e C++
*** c-headers 
#+BEGIN_SRC emacs-lisp
  (defun c-open-header-in-place ()
      "Long names for long bois."
       (local-set-key (kbd "C-c h") 'ff-find-other-file))
  (add-hook 'c-initialization-hook 'c-open-header-in-place)
#+END_SRC
*** irony mode
#+begin_src emacs-lisp 
  (use-package irony
    :ensure t
    :hook
    (c++-mode . irony-mode)
    (c-mode . irony-mode)
    (irony-mode . irony-cdb-autosetup-compile-options))
#+end_src
** resize melhor
#+begin_src emacs-lisp
  (global-set-key (kbd "s-C-<left>") 'shrink-window-horizontally)
  (global-set-key (kbd "s-C-<right>") 'enlarge-window-horizontally)
  (global-set-key (kbd "s-C-<down>") 'shrink-window)
  (global-set-key (kbd "s-C-<up>") 'enlarge-window)
#+end_src
Roubado do witchmacs. Praise Marisa
** salvar clipboard antes de kill
#+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+END_SRC
Isso deveria ser *default*.

*** gdb
#+begin_src emacs-lisp
  (setq gdb-many-windows t
	gdb-show-main t)
  ;; copiado de https://tuhdo.github.io/c-ide.html
  (global-set-key (kbd "<f5>") (lambda ()
				 (interactive)
				 (call-interactively 'compile)))


#+end_src

** Processos assíncronos
   #+begin_src emacs-lisp
    (use-package async
	:ensure t
	:init
	(dired-async-mode 1))
   #+end_src
   Roubado do witchmacs (novamente)


** Dired
   #+begin_src emacs-lisp
     (setq image-dired-thumb-margin 5)
   #+end_src
